GET https://localhost:3000/api/clients
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZSI6eyJpZCI6MSwibmFtZSI6ImZ1bmNpb25hcmlvMSIsImVtYWlsIjoiZnVuYzFAZnVuYzEuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkYkFncDdDbDR3Mm5GU3FYblYzOWZkZTlPdU90S0lDVEluR0hGcGVXb1NwZnJHaUlEMFVnRk8iLCJpc19hZG1pbiI6MX0sImlhdCI6MTY5NjI4NTEwNywiZXhwIjoxNjk2NDU3OTA3fQ.36H77xZGW1XCd6FtUsGHwtBptLRwmiAVayl5PvvNJ5A

###

POST http://localhost:3000/api/auth/client/registration
Content-type: application/json

{
    "name": "clinte8",
    "email":"cliente8@cliente8.com",
    "password": "cliente8"   
}

###

POST http://localhost:3000/api/auth/client/sign_in
Content-type: application/json

{
    "email":"cliente8@cliente8.com",
    "password": "cliente8"   
}

###

PUT http://localhost:3000/api/auth/client?id=155a45f9-8e28-4240-977c-d6bc77baaf72
Content-type: application/json

{
    "name": "Flávio",
    "email":"flavio@flavio",
    "password": "123456"  
   
}

### 

DELETE http://localhost:8080/aluno?id=425ff2ad-d097-46ee-b0ba-071c4abbd37f
