GET http://localhost:3000/api/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZSI6eyJpZCI6MSwibmFtZSI6ImZ1bmNpb25hcmlvMSIsImVtYWlsIjoiZnVuYzFAZnVuYzEuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkYkFncDdDbDR3Mm5GU3FYblYzOWZkZTlPdU90S0lDVEluR0hGcGVXb1NwZnJHaUlEMFVnRk8iLCJpc19hZG1pbiI6MX0sImlhdCI6MTY5NjQ0Nzg1MywiZXhwIjoxNjk2NjIwNjUzfQ.su1h_nUKWw6OZDG0SSdjX8NSaBxU8bEBMWTtEcqW0IY

###

POST http://localhost:3000/api/auth/client/registration
Content-type: application/json

{
    "name": "clinte9",
    "email":"cliente9@cliente9.com",
    "password": "cliente9"   
}

###

POST http://localhost:3000/api/auth/client/sign_in
Content-type: application/json

{
    "email":"cliente8@cliente8.com",
    "password": "cliente8"   
}