GET http://localhost:3000/api/products/search?order=price

###

GET http://localhost:3000/api/sales/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZSI6eyJpZCI6MSwibmFtZSI6ImZ1bmNpb25hcmlvMSIsImVtYWlsIjoiZnVuYzFAZnVuYzEuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkYkFncDdDbDR3Mm5GU3FYblYzOWZkZTlPdU90S0lDVEluR0hGcGVXb1NwZnJHaUlEMFVnRk8iLCJpc19hZG1pbiI6MX0sImlhdCI6MTY5NjQ0Nzg1MywiZXhwIjoxNjk2NjIwNjUzfQ.su1h_nUKWw6OZDG0SSdjX8NSaBxU8bEBMWTtEcqW0IY

###

POST http://localhost:3000/api/sales
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnQiOnsiaWQiOjgsImVtYWlsIjoiY2xpZW50ZThAY2xpZW50ZTguY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkNUlHRFRGZmV0QXhvUzlBNXFZRXNhLjBhQ2RLcFNUUlNnWWNtZXVuV3QvMlF3VVNzcjFTQWEiLCJuYW1lIjoiY2xpbnRlOCJ9LCJpYXQiOjE2OTY0NDkxNDgsImV4cCI6MTY5NjYyMTk0OH0.G32TX_pYj0QN8h0rp-irIa2jMAwqDWBTaSrFcuAY1kg

{
 	"productIDs": [1,2,4,5,6,4]
}

###

POST http://localhost:3000/api/auth/employee/sign_in
Content-type: application/json

{
    "email":"lucio@lucio.com",
    "password": "lucio"   
}